blog/urls.py
from django.urls import path
from . import views

app_name ='blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),

]

portfolio/urls.py
from django.urls import path
from . import views

app_name ='portfolio'

urlpatterns = [
    path('<int:project_id>/', views.detail, name='detail'),

]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('project/', include('portfolio.urls')),
   

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.fields import CharField


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    full_description = models.TextField(blank=True)
    image_main = models.ImageField(upload_to='portfolio/images/')
    image_1 = models.ImageField(upload_to='portfolio/images/', blank=True)
    image_2 = models.ImageField(upload_to='portfolio/images/', blank=True)
    image_3 = models.ImageField(upload_to='portfolio/images/', blank=True)
    url = models.URLField(blank=True)
    github_url = models.URLField(blank=True)
    tech = models.TextField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', { 'blogs':blogs })


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

def detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
   
    return render(request, 'portfolio/detail.html', {'project':project})

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Sam has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}" style=" text-decoration: none;">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>


<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

<a href="{% url 'blog:all_blogs' %}" class="btn btn-primary m-3">Go Back</a>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">


  <link href="https://fonts.googleapis.com/css?family=Jura&display=swap?family=Monoton&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/logo-light.png" %}">

  <title>Sam Klepper</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/logo-light.png" %}" width="40" height="40" class="d-inline-block align-top" alt="Sam's Logo">
        <span class="logo">Sam Klepper</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}"  target="_blank">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/SamKlep" target="_blank">GitHub</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="mailto:samklepdev@gmail.com" target="_blank">Gmail</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <ul class="nav footer flex-column justify-content-center text-center">
    <li class=" nav-item">
      <a class="nav-link active" href="{% url 'home' %}"> <img src="{% static "portfolio/logo-light.png" %}" width="40" height="40" class="d-inline-block align-top" alt="Sam's Logo"></a>
    </li>
    <li class="p-2 nav-item">
      <a class="nav-link" href="https://github.com/SamKlep" target="_blank">GitHub</a>
    </li>
    <li class=" nav-item">
      <a class="nav-link" href="mailto:samklepdev@gmail.com" target="_blank">Gmail</a>
    </li>
    
  </ul>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

portfolio/templates/portfolio/detail.html
{% extends "portfolio/base.html" %} 

{% load static %} 

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ project.title }}</h1>

<p class="lead">{{ project.full_description|safe }}</p>

<br />
<hr />
<br />

<div class="container mb-5">
  <div class="row justify-content-sm-center">
    <div class="card">
 
      <div class="card-body">
        <h5 class="card-title">Tech Used</h5>
        <p class="card-text">{{ project.tech }}</p>
      </div>
      
      <div class="card-body">
        <a href="{{ project.github_url }}" class="card-link" target="_blank">Source Code</a>
        <a href="{{ project.url }}" class="card-link" target="_blank">Visit Site</a>
      </div>
    </div>
  </div>
</div>




<div class="row ">
  <div class="col-md-9 mx-auto">
    <a href="{{ project.image_main.url }}" data-lightbox="home-images">
    <img src="{{ project.image_main.url }}" alt="" class="img-main img-fluid mb-3">
  </a>
    <div class="row mt-3 justify-content-sm-center mb-5 thumbs">
      {% if project.image_1 %}
      <div class="col-sm-2">
        <a href="{{ project.image_1.url }}" data-lightbox="home-images">
          <img src="{{ project.image_1.url }}" alt="" class="img-thumbnail img-fluid">
        </a>
      </div>
      {% endif %}
      {% if project.image_2 %}
      <div class="col-sm-2">
        <a href="{{ project.image_2.url }}" data-lightbox="home-images">
          <img src="{{ project.image_2.url }}" alt="" class="img-fluid">
        </a>
      </div>
      {% endif %}
      {% if project.image_3 %}
      <div class="col-sm-2">
        <a href="{{ project.image_3.url }}" data-lightbox="home-images">
          <img src="{{ project.image_3.url }}" alt="" class="img-fluid">
        </a>
      </div>
      {% endif %}
      </div>
  </div>
</div>


<a href="{% url 'home' %}" class="btn btn-primary mt-5 mb-4">
  Go Back</a>

{% endblock %}

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sam-forward.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Sam Klepper is a <i>JavaScript</i> & <i>Python</i> enthusiast from  Houston, Texas 🤠</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}" target="_blank">
      <img src="{{ project.image_main.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image_main.url }}" class="img-fluid mb-2">
    {% endif %}
    
    <a href="{% url 'portfolio:detail' project.id  %}" style="text-decoration:none">
    <h3>{{ project.title }}</h3>
</a>
    <p>{{ project.description|safe }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}